### ISSUE TITLE
use Plone's default language

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.weather#2]
Google Weather lets you select the language that is going to be used for the weather condition messages; right now we have a field for that in the control panel but it should be cleaner  to use Plone's default language.

**Comment by marcosfromero** [comment]
If Google weather services isn't working, why we should work on this?

**Comment by hvelarde** [comment]
check if Yahoo! Weather provides something like that; if not, just let me know.

**Comment by marcosfromero** [comment]
Yahoo! Weather does not have any plan to provide weather info in other language than English:
http://developer.yahoo.com/forum/General-Discussion-at-YDN/Can-Yahoo-Weather-API-show-by/1275022713000-d78748d9-0247-313b-ad9e-3503b8ea3d07

We could translate the condition as part of this or other package, but I think as part of a different issue.
http://developer.yahoo.com/weather/#codes

**Comment by hvelarde** [comment]
I have created a new issue for that: #11

**Comment by hvelarde** [comment]
Google Weather no longer available
