### ISSUE TITLE
weather data load is broken

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.weather#3]
seems to me that right now the viewlet is trying to get the data from the server every time somebody change the city from the menu; this implementation is broken and is causing many issues: for instance, the viewlet is getting cached and is showing a wrong city on some pages.

the expected behavior should be to cache server side the info, and to load all cities in the viewlet; this way the city selected could be stored on a browser cookie.

**Comment by flecox** [comment]
Done
https://github.com/collective/collective.weather/commit/bcf93ce9e800e6be6f96b38722f994a024bdc16b

**Comment by hvelarde** [comment]
you can do this automatically just by including something like "closes #3" in the commit message...
