### ISSUE TITLE
the portlet must use the new IWeatherInfo utilities

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.weather#30]
currently the weather portlet uses the old utility; we must refactor it to use the new named utilities; also, we should provide a caching mechanism for the portlet as we don't want to update the weather information too often.

**Comment by marcosfromero** [comment]
The portlet calls the old utility:
https://github.com/collective/collective.weather/blob/master/src/collective/weather/portlets/weather.py#L72

Which invokes the new IWeatherInfo utility:
https://github.com/collective/collective.weather/blob/master/src/collective/weather/weather_utility.py#L72
