### ISSUE TITLE
the viewlet must use the new IWeatherInfo utilities

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.weather#31]
currently the weather viewlet uses the old utility; we must refactor it to use the new named utilities; also, we should provide a caching mechanism for the viewlet as we don't want to update the weather information too often and we don't want to update all the cities at the same time, specially if there are many cities listed on it.

we must pay special attention to the later as we have failed in the past here on production sites with web application accelerators, like Varnish, installed.

this is also related with #20.

**Comment by marcosfromero** [comment]
Viewlet code calls weather_utility:
https://github.com/collective/collective.weather/blob/master/src/collective/weather/viewlet.py#L31

And weather_utility invokes new IWeatherInfo utilities:
https://github.com/collective/collective.weather/blob/master/src/collective/weather/weather_utility.py#L72
