### ISSUE TITLE
TypeError: None object cannot be quoted

### ISSUE THREAD

**Issue by fulv** [collective/collective.weather#4]
Could you please add a working example of a location string to either the docs or to the control panel itself?

Not being sure of the required format, I entered the following:

seattle|Seattle|98109

and got the following traceback.  Now I can't even go to the control panel anymore.  This is a vanilla Plone 4.2 site installed using the unified installer.

2012-08-28 12:08:07 ERROR Zope.SiteErrorLog 1346180887.550.331227773688 http://localhost:8080/Plone/plone_control_panel
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in **call**
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 79, in pt_render
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
- URL: file:/Users/harvey/Plone4.2/buildout-cache/eggs/Products.CMFPlone-4.2.0.1-py2.7.egg/Products/CMFPlone/skins/plone_prefs/plone_control_panel.pt
- Line 4, Column 0
- Expression: <PathExpr standard:u'context/@@overview-controlpanel'>
- Names:
    {'container': <PloneSite at /Plone>,
     'context': <PloneSite at /Plone>,
     'default': <object object at 0x10029db40>,
     'here': <PloneSite at /Plone>,
     'loop': {},
     'nothing': None,
     'options': {'args': ()},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x10af63f70>,
     'request': <HTTPRequest, URL=http://localhost:8080/Plone/plone_control_panel>,
     'root': <Application at >,
     'template': <FSPageTemplate at /Plone/plone_control_panel>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>}
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module Products.PageTemplates.Expressions, line 117, in render
  Module plone.app.controlpanel.overview, line 40, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in **call**
  Module Products.Five.browser.pagetemplatefile, line 59, in **call**
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
- URL: file:/Users/harvey/Plone4.2/buildout-cache/eggs/plonetheme.sunburst-1.2.5-py2.7.egg/plonetheme/sunburst/skins/sunburst_templates/main_template.pt
- Line 62, Column 12
- Expression: <StringExpr u'plone.portaltop'>
- Names:
    {'args': (),
     'container': <PloneSite at /Plone>,
     'context': <PloneSite at /Plone>,
     'default': <object object at 0x10029db40>,
     'here': <PloneSite at /Plone>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x10a477e10>,
     'request': <HTTPRequest, URL=http://localhost:8080/Plone/plone_control_panel>,
     'root': <Application at >,
     'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x10172f890>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>,
     'view': <Products.Five.metaclass.OverviewControlPanel object at 0x10af6a6d0>,
     'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x10af6a950>}
  Module zope.contentprovider.tales, line 80, in **call**
  Module plone.app.viewletmanager.manager, line 154, in render
  Module plone.app.viewletmanager.manager, line 85, in render
  Module zope.browserpage.simpleviewclass, line 44, in **call**
  Module Products.Five.browser.pagetemplatefile, line 125, in **call**
  Module Products.Five.browser.pagetemplatefile, line 59, in **call**
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
- URL: /Users/harvey/Plone4.2/buildout-cache/eggs/plone.app.layout-2.2.6-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
- Line 2, Column 4
- Expression: <StringExpr u'plone.portalheader'>
- Names:
    {'args': (),
     'container': <PloneSite at /Plone>,
     'context': <PloneSite at /Plone>,
     'default': <object object at 0x10029db40>,
     'here': <PloneSite at /Plone>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x10a4779f0>,
     'request': <HTTPRequest, URL=http://localhost:8080/Plone/plone_control_panel>,
     'root': <Application at >,
     'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x107199ed0>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>,
     'view': <Products.Five.viewlet.viewlet.SimpleViewletClass from /Users/harvey/Plone4.2/buildout-cache/eggs/plone.app.layout-2.2.6-py2.7.egg/plone/app/layout/viewlets/portal_header.pt object at 0x10af6ad10>,
     'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x10af6add0>}
  Module zope.contentprovider.tales, line 77, in **call**
  Module zope.viewlet.manager, line 112, in update
  Module zope.viewlet.manager, line 118, in _updateViewlets
  Module collective.weather.viewlet, line 137, in update
  Module collective.weather.viewlet, line 73, in update_google_weather_info
  Module pywapi, line 53, in get_weather_from_google
  Module urllib, line 1255, in quote
  TypeError: None object cannot be quoted

**Comment by hvelarde** [comment]
I think this is a working example: **caracas|Caracas|Caracas, Venezuela**

in your case you should probably use **seattle|Seattle|Seattle, WA**

in the case of Google Weather the second parameter is the name showed in the viewlet and the third is the search string used internaly by the service (correct me if I'm wrong, @frapell, and please make the code more robust and update the documentation when you have time).

we are still trying to figure out how to solve this in a cleaner way, any suggestion?

**Comment by hvelarde** [comment]
are you using master or the Alpha release, @fulv?

**Comment by fulv** [comment]
I tried your Caracas example, and get the same error.  When I looked at http://code.google.com/p/python-weather-api/#Google_Weather, it seemed to suggest that zipcodes would be accepted.

I merely added "collective.weather" to the eggs =, here are the version pins reported by dumppickedversions:

collective.js.jqueryui                = 1.8.16.8
collective.weather                    = 1.0a1
collective.z3cform.widgets            = 1.0a3
pywapi                                = 0.2.2

**Comment by hvelarde** [comment]
ok, thanks... @frapell will take care of this soon :-)

**Comment by hvelarde** [comment]
@fulv there's a new release of the package; could you please test it and see if it works for you now?

**Comment by fulv** [comment]
@hvelarde  Yes, the first tab (Yahoo?) works now.
