### ISSUE TITLE
add a portlet to display the weather

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.weather#9]
besides the viewlet, a portlet would be useful for some people.

**Comment by marcosfromero** [comment]
Should the portlet have configuration options or it should take configuration from Weather configlet?

**Comment by hvelarde** [comment]
probably time-to-live; then we can memoize the portlet rendering and update the weather info periodically.

BTW, I think the portlet should only show the first city configured.

**Comment by marcosfromero** [comment]
Don't like the idea of showing only the first city.
We could provide a select widget to choose one of the configured cities.

**Comment by hvelarde** [comment]
keep it simple in this iteration
